# Generated by Django 5.1.6 on 2025-04-12 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('driver_name', models.CharField(max_length=255)),
                ('car_number_plate', models.CharField(max_length=20)),
                ('date_of_arrival', models.DateTimeField(blank=True, null=True)),
                ('date_of_departure', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=50, null=True)),
                ('api_key', models.CharField(default='IASMINA', editable=False, max_length=255)),
            ],
        ),
    ]
