# Generated by Django 5.1.6 on 2025-05-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'În Așteptare'), ('paid', 'Plătit'), ('failed', 'Eșuat')], default='pending', max_length=10, null=True),
        ),
    ]
