# Generated by Django 5.1.6 on 2025-05-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_alter_driver_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('pending', 'In asteptare'), ('paid', 'Platit'), ('failed', 'Esuat')], default='pending', max_length=10, null=True),
        ),
    ]
